name: Terraform

on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: setup AWS CLI
      run: |
        mkdir ~/.aws/credentials
        echo '[administrator]' >> ~/.aws/credentials
        echo 'aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}' >> ~/.aws/credentials
        echo 'aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}' >> ~/.aws/credentials
        aws-region: us-west-2

    - name: Terraform Initialize
      run: terraform init

    - name: Terraform Plan
      run: terraform plan